### ISSUE TITLE
Throttle breaks sensors

### ISSUE THREAD

**Issue by cserem** [KinDR007/VictronMPPT-ESPHOME#48] opened 2022-05-29 11:58 UTC
Hello!

The commit https://github.com/KinDR007/VictronMPPT-ESPHOME/commit/be1c30bfd2e9d4e97b3d63ff97f87f0c2425782b breaks the update of sensors.

I have tried setting the throttle parameter multiple ways, even not setting it, but it doesn't work.

Reverting to https://github.com/KinDR007/VictronMPPT-ESPHOME/commit/835dbadd25b4e7004d43fdbc263d83c0caa42282  fixes the issue.

Could you please investigate?

Thanks 
M

**Comment by syssi** [comment] 2022-05-29 12:02
Sorry for the mess. I will care about a fix. Could you help testing?

**Comment by syssi** [comment] 2022-05-29 12:07
Okay, I know what's going on. My approach is completely wrong.

**Comment by cserem** [comment] 2022-05-29 12:09
Sure thing, just write here and  I will test as soon as possible!

**Comment by syssi** [comment] 2022-05-29 13:03
I've pushed a fix. Please give it a try by using this feature branch:

```
external_components:
  - source: github://syssi/esphome-victron-vedirect@fix-throtte
```

**Comment by cserem** [comment] 2022-05-29 13:22
This seems to fix the issue!

Thank you!

**Comment by syssi** [comment] 2022-05-29 13:23
Could you test the throttle (f.e. `1s` vs. `10s`)?

**Comment by syssi** [comment] 2022-05-29 13:54
I was able to test it on my workbench. This time it should work as intended.

**Closed** 2022-05-29 14:03 UTC

**Comment by cserem** [comment] 2022-05-29 14:15
Yes, throttle parameter works as intended, if set. If unconfigured it defaults to 1s properly.
